version: '3'
services:
  mininet:
    build:
      context: .
    image: mininet
    tty: true
    privileged: true
    environment:
     - DISPLAY
    network_mode: "host"
#    volumes:
#     - /lib/modules:/lib/modules
